DROP TABLE IF EXISTS guilds;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS role_data;
DROP TABLE IF EXISTS channels;
DROP TABLE IF EXISTS channel_overwrites;
DROP TABLE IF EXISTS channel_recipients;