ALTER TABLE roles
    ALTER COLUMN gradient TYPE BOOLEAN USING FALSE,
    ALTER COLUMN gradient SET DEFAULT FALSE,
    ALTER COLUMN gradient SET NOT NULL,
    DROP COLUMN IF EXISTS icon;

ALTER TABLE channels
    DROP COLUMN IF EXISTS color,
    DROP COLUMN IF EXISTS gradient;

DROP TYPE IF EXISTS gradient_type;
DROP TYPE IF EXISTS gradient_stop;
