CREATE TABLE IF NOT EXISTS bots (
    user_id BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    owner_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    default_permissions BIGINT NOT NULL DEFAULT 0,
    flags INTEGER NOT NULL DEFAULT 0
);